spring:
  application:
    name: scorecard

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:
        hbm2ddl:
          auto: update

  datasource:
    username: scorecard_user
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/scorecard_db
    driver-class-name: org.postgresql.Driver

logging:
  level:
    .: INFO #set default logging to info level for all packages
    org.springframework: INFO #specific log level for specified package